spring:
  application:
    name: transacciones

  #Config postgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/CompraVenta
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
  #Jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false

server:
  port: 8080




jwt:
  secret: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NzA0MTk3NzEsImV4cCI6MTc3MTAyNDU3MSwianRpIjoiMzhjNThjN2UtMDM1Ny00NGYxLWJkNDgtM2IyNDZlN2IxNWUzIiwiaXNzIjoiYXBpLmV4YW1wbGUuY29tIiwic3ViIjoidXNlcl83MjM2IiwiYXVkIjoiaHR0cHM6Ly9leGFtcGxlLmNvbSJ9.E71cAhlnILALEd58EyQVUq7TiUfmu5BzrKZkRQcD91I





